main = ".open-next/worker.js"
name = "home-page"
compatibility_date = "2025-07-14"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[observability]
enabled = true